### ISSUE TITLE
Encoding issues with zopen-curl that were not present with Rocket-curl

### ISSUE THREAD

**Issue by depemco** [ZOSOpenTools/curlport#26]
When using a certificate with type P12 in a curl command to make a API-request to z/OSMF, the encoding goes wrong in the response.
```
**2024-04-02 15:07:33**  + curl -k -X PUT --data { "file" : "/path/to/file.job" } --cert-type P12 --cert \*\*\*\*:\*\*\*\* -w %{http\_code} -H Accept: application/json -H Content-Type: application/json -H X-CSRF-ZOSMF-HEADER: true [https://url-to-zosmf/zosmf/restjobs/jobs](https://url-to-zosmf/zosmf/restjobs/jobs) 
**2024-04-02 15:07:33**    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
**2024-04-02 15:07:33**                                   Dload  Upload   Total   Spent    Left  Speed
**2024-04-02 15:07:35**  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   139    0     0  100   139      0    131  0:00:01  0:00:01 --:--:--   131
100   621    0   482  100   139    338     97  0:00:01  0:00:01 --:--:--   436
100   621    0   482  100   139    338     97  0:00:01  0:00:01 --:--:--   436
**2024-04-02 15:07:35** \[Pipeline\] echo[](https://url-to-jenkins/console#)
**2024-04-02 15:07:35**  responseCode: 
**2024-04-02 15:07:35** \[Pipeline\] echo[](https://url-to-jenkins/console#)
**2024-04-02 15:07:35**  responseBody: #?Ï>ÁÊä+(øÇ/ (this goes on for a while, so I truncated it)
```
When using Basic-Auth instead of a certificate, there are no encoding problems at all. What could trigger this encoding problem?

curl version `curl 8.5.0 (i370-ibm-openedition) libcurl/8.5.0 OpenSSL/3.2.0`.

This is no issue when using the Rocket curl, only with the Z Open Tools curl. The Rocket version in use: `curl 7.66.0 (i370-ibm-openedition) libcurl/7.66.0 OpenSSL/1.0.2l zlib/1.2.11 libssh2/1.8.0 nghttp2/1.33.0`

**Comment by depemco** [comment]
```
t ISO8859-1   T=on  curlrocket.txt
- untagged    T=off curlzopen.txt
```

The content of curlzopen.txt:
```
000{"rc":4,"reason":32,"category":6,"message":"Error parsing JSON input"}400
```

**Comment by mfsysprog** [comment]
We are running these shell commands through a jenkins pipeline script in a sh step. 
So this is not native behaviour.

This is implemented in:
https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/768003e07199845c8a8e1540bb0edba268a89a6e/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java
with most of the code in:
https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/768003e07199845c8a8e1540bb0edba268a89a6e/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java#L104

We start the jenkins agent running on our system with the following JVM settings:
```
-Xquickstart -Dfile.encoding=utf-8 -Djavax.net.ssl.trustStore="/path/to/some/truststore" -Djavax.net.ssl.trustStorePassword=somepassword
```
and the following start agent command:
```
export _BPXK_AUTOCVT=ON && . /etc/zopen-beta-config && export JAVA_HOME=/usr/lpp/java/J17.0_64 && env|sort && 
```
and the following Suffix start agent command (note the leading space):
```
 -text
 ```
 
This is an example pipeline script to show the behaviour:
```
#!groovy

pipeline {
    agent { label ('master')}
    options {
        disableConcurrentBuilds()
        timeout(time: 8, unit: 'HOURS')
    }
    stages {
        stage ('Testing Something') {
            agent { label ('HOST')}
            options {
                skipDefaultCheckout()
            }
            steps {
               script {
                    output = sh(returnStdout: true, script: "/link/to/rocket/curl --version")
                    output2 = sh(returnStdout: true, script: "curl --version")
					println "response.rocket: " + output
					println "response.zopen: " + output2
                }
            }
        }
    }
    post {
        always {
            echo 'One way or another, I have finished'
            
        }
    }
}
```

It seems that whenever the first command is running in ascii mode that the output gets garbled.
When I change the second command to this the output is normal:
```
output2 = sh(returnStdout: true, script: "curl --version | cat")
```
So the problem is that the autoconversion is not applied, but I'm not sure yet why that happens.
According to the comment in the jenkins code for the shell step the stdout goes through a file first, so there probably is something there, but I have not yet found the specifics.

**Comment by mfsysprog** [comment]
Something else I noticed, this gives correct output:
```
output2 = sh(returnStdout: true, script: "env && curl --version")
```
this gives garbled output:
```
output2 = sh(returnStdout: true, script: "curl --version && env")
```
so I guess the pcssid of the initial command influences the conversion

**Comment by mfsysprog** [comment]
Docu for the sh step is at https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/

**Comment by mfsysprog** [comment]
The "ð" is x'F0', the return code for the step that is in ebcdic. So this is why specifying an encoding does not work...

**Comment by IgorTodorovskiIBM** [comment]
As far as I know, Java does not run with auto-conversion enabled. In this case, jenkins (java) is probably spawning a new process and reading the output via the pipe and expecting output in UTF8 since you have ` -Dfile.encoding=utf-8` specified.

In zoslib, we tag the stdio fds to 1047 at startup if they're not tagged. But you can also set it using `export __STDIN_CCSID=819` for example.
```
2649   if (get_env_var("__STDIN_CCSID", ccsid))
2650     __set_autocvt_on_fd_stream(STDIN_FILENO, std::stoul(ccsid), 1, false);
2651   else
2652     __set_autocvt_on_fd_stream(STDIN_FILENO, 1047, 1, true);
2653
2654   if (get_env_var("__STDOUT_CCSID", ccsid))
2655     __set_autocvt_on_fd_stream(STDOUT_FILENO, std::stoul(ccsid), 1, false);
2656   else
2657     __set_autocvt_on_fd_stream(STDOUT_FILENO, 1047, 1, true);
2658
2659   if (get_env_var("__STDERR_CCSID", ccsid))
2660     __set_autocvt_on_fd_stream(STDERR_FILENO, std::stoul(ccsid), 1, false);
2661   else
2662     __set_autocvt_on_fd_stream(STDERR_FILENO, 1047, 1, true);

```

Does it work with:
```
output2 = sh(returnStdout: true, script: "__STDIN_CCSID=819 curl --version")
```

**Comment by mfsysprog** [comment]
```output2 = sh(returnStdout: true, script: "__STDOUT_CCSID=1047 curl --version")```` does the trick.
I guess that whenever the temporary jenkins-result.txt file is read back in by Jenkins it assumes platform encoding. It doesn't use fileencoding=utf-8 it seems.

**Comment by mfsysprog** [comment]
I also testing adding ```export __STDOUT_CCSID=1047``` to the start agent command for the node and that works also.
So I guess that will be our permanent solution for this.
I'm ok to close this issue.

**Comment by IgorTodorovskiIBM** [comment]
Interesting, so that means in the default case, this condition: https://github.com/ibmruntimes/zoslib/blob/main/src/zos-char-util.cc#L577C1-L578C1
is false:
```
  if (!on_untagged_only || (!isatty(fd) && 0 == __getfdccsid(fd))) {
    fcntl(fd, F_CONTROL_CVT, &req);
    fcntl(fd, F_SETTAG, &tag);
  }
```

**Comment by IgorTodorovskiIBM** [comment]
So either the pipe is tagged, but auto-conversion is disabled or it's a tty

**Comment by mfsysprog** [comment]
The comment in the Jenkins code says that the stdout is redirected, so I guess at the time of the initial open it as allocated to a tty

**Comment by mfsysprog** [comment]
In zos-io.cc in the open_ascii en fopen_ascii functions conversion is always enabled on a tty. Any reason why it is not enabled on a tty in this part of the code?

**Comment by IgorTodorovskiIBM** [comment]
I'm not sure, but I noticed that we didn't have that check in the zopen branch of zoslib: https://github.com/ibmruntimes/zoslib/blob/zopen/src/zos-char-util.cc#L568

Do builds of curl pre Dec 2023 work? https://github.com/ZOSOpenTools/curlport/releases/tag/STABLE_curlport_1619 . These were built using the zopen branch of zoslib

**Comment by depemco** [comment]
We are using the builds curl-8.4.0.20231011_155722.zos and curl-8.5.0.20240130_020020.zos for the tests.

**Comment by mfsysprog** [comment]
I tested with curl-8.4.0.20231011_155722.zos, but that version has the same issue and can also be solved with ```export __STDOUT_CCSID=1047```
