### ISSUE TITLE
Chicken - egg?

### ISSUE THREAD

**Issue by phaumer** [ZOSOpenTools/curlport#7]
The release notes require curl to install curl? Should there also be alternative instructions?

**Comment by phaumer** [comment]
Found it at https://zosopentools.github.io/meta/#/Guides/Pre-req

**Comment by MikeFultonDev** [comment]
we will be overhauling the docs pretty much continually 😁 
hopefully the `zopen-setup` is a good alternative now. Please re-open if you think there's specifics we should tackle
